"""Companion files generated from data only. Never hand-edit the output."""
from __future__ import annotations

import datetime as dt
from pathlib import Path
from typing import Any

from .lint import LintReport, PlaceholderInfo
from .loader import GuideData
from .model import TAG_NAMES
from .resolve import Resolved, plain_text

HEADER = "_Generated by guidekit from the guide's YAML on {date}. Do not edit; change the YAML and run `guidekit docs`._\n"


def _md_cell(text: Any) -> str:
    return str(text or "").replace("|", "\\|").replace("\n", " ")


def _pages(nums: list[int]) -> str:
    return ", ".join(str(n) for n in nums) or "(not on a page)"


def page_titles(data: GuideData, res: Resolved) -> list[tuple[int, str, str]]:
    """(number, id, readable title) in page order."""
    out = []
    for p in data.plan_pages:
        if p.type == "cover":
            title = "Cover"
        elif p.type == "sources":
            title = p.title or data.theme.tokens["labels"]["sources_title"]
        else:
            title = plain_text(p.title or p.id, res)
        out.append((res.page_no[p.id], p.id, title))
    return out


# --------------------------------------------------------------------------- sources.md

def sources_md(data: GuideData, res: Resolved, today: dt.date) -> str:
    L = [f"# Sources: {data.guide.title}", "", HEADER.format(date=today.isoformat()), ""]
    L += ["## Claims", "", "| Claim | Tag | Sources | Page(s) |", "|---|---|---|---|"]
    order = res.claim_order + [c.id for c in data.claims if c.id not in res.claim_order]
    for cid in order:
        c = data.claim_by_id.get(cid)
        if not c:
            continue
        srcs = ", ".join(f"[{res.source_no[s]}] {s}" if s in res.source_no else s for s in c.sources) or "none"
        L.append(f"| {_md_cell(c.text)} `{c.id}` | {TAG_NAMES[c.tag]} | {_md_cell(srcs)} | {_pages(res.claim_pages.get(cid, []))} |")
    L += ["", "## Sources", "", "| # | Source | Type | Verified how | Verified on | Bias | Page(s) |", "|---|---|---|---|---|---|---|"]
    for sid in res.cited_ids:
        s = data.source_by_id[sid]
        cite = f"{s.citation} {s.venue or ''} <{s.url}>".strip()
        bias = "none" if s.bias == "none" else f"**{s.bias}**"
        L.append(f"| {res.source_no[sid]} | {_md_cell(cite)}<br>_Says:_ {_md_cell(s.says)} | {s.type} | "
                 f"{_md_cell(s.verified_how)} | {s.verified_on} | {bias} | {_pages(res.source_pages.get(sid, []))} |")
    consulted = [s for s in data.sources if s.consulted_only]
    unused = [s for s in data.sources if not s.consulted_only and s.id not in res.source_no]
    L += ["", "## Consulted, not cited", ""]
    if consulted or unused:
        for s in consulted + unused:
            note = "consulted" if s.consulted_only else "verified but not used on any page"
            L.append(f"- {s.citation} <{s.url}> ({s.type}, {note}). {s.says}")
    else:
        L.append("- none")
    L += ["", "## Known weak spots", ""]
    weak = []
    for c in data.claims:
        if c.id not in res.claim_order:
            continue
        if c.caveat:
            weak.append(f"- `{c.id}` ({TAG_NAMES[c.tag]}): {c.caveat}")
        if c.tag == "S":
            weak.append(f"- `{c.id}` is an ESTIMATE: a range across sources, not a measured value.")
        if c.tag == "N":
            weak.append(f"- `{c.id}` NO DATA FOUND: {c.text}")
    for sid in res.cited_ids:
        s = data.source_by_id[sid]
        if s.bias != "none":
            weak.append(f"- Source [{res.source_no[sid]}] `{sid}` has a commercial interest: {s.bias}.")
        if s.type == "news":
            weak.append(f"- Source [{res.source_no[sid]}] `{sid}` is press coverage, not the primary study.")
    L += weak or ["- none recorded"]
    return "\n".join(L) + "\n"


# --------------------------------------------------------------------------- assumptions.md

def assumptions_md(data: GuideData, today: dt.date) -> str:
    L = [f"# Assumptions: {data.guide.title}", "", HEADER.format(date=today.isoformat()), ""]
    L += ["## Decisions", "", "| Decision | Why | Risk | Needs creator OK |", "|---|---|---|---|"]
    for a in data.assumptions:
        L.append(f"| {_md_cell(a.decision)} `{a.id}` | {_md_cell(a.why)} | {a.risk} | {'yes' if a.confirm else 'no'} |")
    if not data.assumptions:
        L.append("| none | | | |")
    L += ["", "## Change log", ""]
    for c in data.log.changes:
        L.append(f"- **{c.date}** {c.instruction}" + (f": {c.summary}" if c.summary else ""))
        for k in c.knock_on:
            L.append(f"  - knock-on: {k}")
    if not data.log.changes:
        L.append("- no revisions yet")
    L += ["", "## QA log", ""]
    for q in data.log.qa:
        notes = f" ({'; '.join(q.notes)})" if q.notes else ""
        L.append(f"- **{q.date}** {q.result.upper()}: {q.pages} pages, {q.errors} errors, {q.warnings} warnings{notes}")
    if not data.log.qa:
        L.append("- no builds logged yet")
    return "\n".join(L) + "\n"


# --------------------------------------------------------------------------- creator-input-list.md

def creator_questions(data: GuideData, lint_report: LintReport, res: Resolved) -> list[str]:
    """One voice-note-friendly question per open placeholder or confirm item."""
    titles = {pid: t for _, pid, t in page_titles(data, res)}
    name = data.guide.creator.name
    qs: list[str] = []

    def where(p: PlaceholderInfo) -> str:
        return f"(page {p.page_no}, \"{titles.get(p.page_id, p.page_id)}\")"

    for p in lint_report.placeholders:
        prompt = plain_text(p.prompt, res).rstrip()
        if p.kind == "confirm":
            draft = plain_text(p.draft or "", res).rstrip(". ")
            qs.append(f"The brief says: \"{draft}\". Is that right, or how would you put it? {where(p)}"
                      if draft else f"Can you confirm this? {prompt} {where(p)}")
        elif p.kind == "photo":
            qs.append(f"Could you send a photo for this? {prompt} {where(p)}")
        elif p.kind == "cta":
            qs.append(f"How should people take the next step? {prompt} {where(p)}")
        else:
            qs.append(f"{prompt} {where(p)}")
    for a in data.assumptions:
        if a.confirm:
            qs.append(f"I assumed: {a.decision}. Is that OK? (applies to the whole guide)")
    if data.guide.cta.type == "undecided" and not any(p.kind == "cta" for p in lint_report.placeholders):
        qs.append(f"What should the last page point people to: a comment keyword or a waitlist link?")
    return qs


def creator_input_md(data: GuideData, lint_report: LintReport, res: Resolved, today: dt.date) -> str:
    name = data.guide.creator.name
    qs = creator_questions(data, lint_report, res)
    inv = lint_report.inventory()
    L = [f"# What I need from {name}", "", HEADER.format(date=today.isoformat()), "",
         f"Open items: {len(qs)} ({', '.join(f'{v} {k}' for k, v in sorted(inv.items())) or 'no placeholders'}).",
         "A voice note answering these in order is perfect.", ""]
    L += [f"{i}. {q}" for i, q in enumerate(qs, 1)] or ["Nothing open."]
    return "\n".join(L) + "\n"


# --------------------------------------------------------------------------- qa-report.md

def qa_report_md(data: GuideData, lint_report: LintReport, build: Any, today: dt.date) -> str:
    L = [f"# QA report: {data.guide.title}", "", HEADER.format(date=today.isoformat()), ""]
    errors = lint_report.errors + (build.errors if build else [])
    warns = lint_report.warnings + (build.warnings if build else [])
    verdict = "FAIL" if errors else ("PASS with warnings" if warns else "PASS")
    L += [f"**{verdict}**: {len(errors)} errors, {len(warns)} warnings.", ""]
    if build:
        full = build.checks.get("full", {}).get("pages", [])
        L += ["## Pages", "", "| # | Page | Usage | Fit | Notes |", "|---|---|---|---|---|"]
        fits = build.fits.get("full", {})
        for p in full:
            f = fits.get(p["id"])
            fit = "as written" if not f or f.round == 0 else f"space {f.space:g} / font {f.font:g}"
            L.append(f"| {p['no']} | {p['id']} | {p['usage']:.0%} | {fit} | {_md_cell(f.note if f and f.round else '')} |")
        L += ["", "## PDF", ""]
        for mode, st in build.pdf_stats.items():
            L.append(f"- {mode}: {st['pages']} pages, {st['links']} links, {st['text_chars']} characters of extractable text")
        L += ["", "## Contact sheets (look at these before calling it done)", ""]
        L += [f"- `{s.relative_to(data.root)}`" for s in build.sheets] or ["- none (built without PNGs)"]
    L += ["", "## Lint", ""]
    L += [f"- {i}" for i in lint_report.issues] or ["- clean"]
    if build:
        L += ["", "## Render QA", ""]
        L += [f"- {i}" for i in build.issues if i.code != "lint"] or ["- clean"]
    inv = lint_report.inventory()
    L += ["", "## Placeholder inventory", ""]
    L += [f"- {k}: {v}" for k, v in sorted(inv.items())] or ["- none"]
    return "\n".join(L) + "\n"


def write_docs(data: GuideData, lint_report: LintReport, res: Resolved, build: Any = None,
               today: dt.date | None = None) -> list[Path]:
    today = today or dt.date.today()
    ddir = data.out / "docs"
    ddir.mkdir(parents=True, exist_ok=True)
    files = {
        "sources.md": sources_md(data, res, today),
        "assumptions.md": assumptions_md(data, today),
        "creator-input-list.md": creator_input_md(data, lint_report, res, today),
        "qa-report.md": qa_report_md(data, lint_report, build, today),
    }
    paths = []
    for name, text in files.items():
        path = ddir / name
        path.write_text(text, encoding="utf-8")
        paths.append(path)
    return paths
