"""Pydantic schemas for every YAML file in a guide folder.

YAML is the source of truth. Unknown keys are errors (extra="forbid") so a typo
fails loudly instead of silently dropping content.
"""
from __future__ import annotations

import datetime as dt
from typing import Annotated, Any, ClassVar, Literal, Union

from pydantic import (
    BaseModel,
    BeforeValidator,
    ConfigDict,
    Discriminator,
    Field,
    Tag,
    create_model,
    model_validator,
)


class Strict(BaseModel):
    model_config = ConfigDict(extra="forbid")


# --------------------------------------------------------------------------- tags

TagCode = Literal["R", "C", "E", "S", "N"]
TAG_ORDER: tuple[str, ...] = ("R", "C", "E", "S", "N")
TAG_NAMES = {
    "R": "RESEARCH",
    "C": "COACH CONSENSUS",
    "E": "MY EXPERIENCE",
    "S": "ESTIMATE",
    "N": "NO DATA FOUND",
}

# Marker metadata for str fields that hold ids, not prose. The walker in
# resolve.py uses it to tell references apart from headings.
CLAIM_REF = {"ref": "claim"}
SLOT_REF = {"ref": "image"}
PAGE_REF = {"ref": "page"}
ClaimId = Annotated[str, Field(json_schema_extra=CLAIM_REF)]
SlotId = Annotated[str, Field(json_schema_extra=SLOT_REF)]


# --------------------------------------------------------------------------- guide.yaml

class Creator(Strict):
    handle: str
    name: str
    email: str | None = None


class Cta(Strict):
    type: Literal["comment", "waitlist", "undecided"] = "undecided"
    value: str | None = None


GuideStatus = Literal["draft", "sample_sent", "awaiting_answers", "paid_discussion", "sold"]


class Guide(Strict):
    id: str
    creator: Creator
    title: str
    kicker: str
    cover_title: list[str]
    topic: str
    audience: str
    niche: str = "general"
    spelling: Literal["US", "UK"] = "US"
    theme: str = "default"
    tokens: dict[str, Any] = Field(default_factory=dict)  # per-guide token overrides
    character: str = ""
    page_plan: list[str]
    preview_pages: list[str] = Field(default_factory=list)
    preview_include_sources: bool = False
    sample_cap_pages: int = 10
    promised_by: dt.date | None = None
    status: GuideStatus = "draft"
    cta: Cta = Field(default_factory=Cta)
    email_next_step: bool = True


# --------------------------------------------------------------------------- sources / claims

SourceType = Literal[
    "peer_reviewed", "position_stand", "case_report", "official_standard",
    "education", "coaching_blog", "news",
]
Bias = Literal["none", "own_plan", "sells_app", "sells_equipment", "sells_service"]


class Source(Strict):
    id: str
    number: int | None = None
    citation: str
    venue: str | None = None
    url: str
    short: str | None = None
    type: SourceType
    verified_how: str
    verified_on: dt.date
    bias: Bias = "none"
    says: str
    consulted_only: bool = False  # listed under "consulted, not cited"; must not be cited


class Claim(Strict):
    id: str
    tag: TagCode
    text: str
    sources: list[str] = Field(default_factory=list)
    caveat: str | None = None


# --------------------------------------------------------------------------- assumptions / images / log

class Assumption(Strict):
    id: str
    decision: str
    why: str
    risk: Literal["low", "medium", "high"] = "low"
    confirm: bool = False  # True → becomes a creator question
    date: dt.date | None = None


class ImageJob(Strict):
    id: str
    variant: int | None = None
    file: str | None = None
    verdict: Literal["pending", "pick", "reject"] = "pending"
    reason: str | None = None
    credits: float | None = None


class ImageSlot(Strict):
    id: str
    scene: str
    action: str = ""
    view: str = "Three-quarter side view"
    checks: list[str] = Field(default_factory=list)
    file: str | None = None  # relative to guide dir, e.g. images/cover.png
    status: Literal["todo", "generated", "picked", "placeholder"] = "todo"
    prompt: str | None = None  # generated by `guidekit images prompts`
    jobs: list[ImageJob] = Field(default_factory=list)


class ImagesFile(Strict):
    style_lock: str | None = None  # None → theme default
    cover_ref: str | None = None  # file of the chosen cover, used as image reference
    credits_used: float = 0
    slots: list[ImageSlot] = Field(default_factory=list)


class ChangeEntry(Strict):
    date: dt.date
    instruction: str
    summary: str = ""
    knock_on: list[str] = Field(default_factory=list)


class QAEntry(Strict):
    date: dt.date
    result: Literal["pass", "warn", "fail"]
    pages: int
    errors: int = 0
    warnings: int = 0
    notes: list[str] = Field(default_factory=list)


class LogFile(Strict):
    changes: list[ChangeEntry] = Field(default_factory=list)
    qa: list[QAEntry] = Field(default_factory=list)


# --------------------------------------------------------------------------- lines

class ClaimLine(Strict):
    claim: ClaimId
    text: str | None = None  # display wording; defaults to claim.text


class EditorialLine(Strict):
    editorial: Literal[True]
    text: str
    implicit: bool = Field(default=False, exclude=True)  # came from a component-level editorial flag


PlaceholderKind = Literal["creator", "photo", "cta", "confirm"]


class PlaceholderLine(Strict):
    placeholder: PlaceholderKind
    prompt: str
    label: str | None = None  # short title shown in the box
    draft: str | None = None  # confirm: what the brief says, awaiting approval


class BareLine(Strict):
    """A plain string where a tagged line was required. Always a lint failure
    unless the enclosing component sets `editorial: true`."""
    text: str


def _line_kind(v: Any) -> str | None:
    if isinstance(v, str):
        return "bare"
    if isinstance(v, dict):
        for key in ("claim", "editorial", "placeholder"):
            if key in v:
                return key
        if set(v) == {"text"}:
            return "bare"
        return None
    return {
        ClaimLine: "claim", EditorialLine: "editorial",
        PlaceholderLine: "placeholder", BareLine: "bare",
    }.get(type(v))


def _to_bare(v: Any) -> Any:
    return {"text": v} if isinstance(v, str) else v


Line = Annotated[
    Union[
        Annotated[ClaimLine, Tag("claim")],
        Annotated[EditorialLine, Tag("editorial")],
        Annotated[PlaceholderLine, Tag("placeholder")],
        Annotated[BareLine, BeforeValidator(_to_bare), Tag("bare")],
    ],
    Discriminator(_line_kind),
]
LINE_TYPES = (ClaimLine, EditorialLine, PlaceholderLine, BareLine)


class Component(Strict):
    """Base for block bodies. `editorial: true` marks every bare string inside the
    component as editorial (instructions/opinion) so tables stay readable."""
    editorial: bool = False

    @model_validator(mode="after")
    def _promote_bare(self) -> "Component":
        if self.editorial:
            _promote(self)
        return self


def _promote(obj: Any) -> Any:
    if isinstance(obj, BareLine):
        return EditorialLine(editorial=True, text=obj.text, implicit=True)
    if isinstance(obj, list):
        for i, item in enumerate(obj):
            obj[i] = _promote(item)
        return obj
    if isinstance(obj, BaseModel):
        for name in type(obj).model_fields:
            val = getattr(obj, name)
            new = _promote(val)
            if new is not val:
                object.__setattr__(obj, name, new)
        return obj
    return obj


# --------------------------------------------------------------------------- components

Tone = Literal["plain", "accent", "teal", "sand", "dark"]


class Card(Component):
    title: str | None = None
    lines: list[Line] = Field(default_factory=list)
    tone: Tone = "plain"
    icon: Literal["none", "check", "cross", "flag", "info"] = "none"


class Facts(Component):
    title: str | None = None
    items: list[Line]
    numbered: bool = False
    show_tags: bool = True


class Para(Component):
    line: Line
    size: Literal["body", "lead", "small"] = "body"


class Verdict(Component):
    label: str = "Verdict"
    lines: list[Line]


class Myth(Component):
    myth: Line
    truth: list[Line]
    severity: Literal["high", "medium", "low"] = "medium"
    severity_label: str | None = None  # default from theme tokens


class LevelScale(Component):
    title: str | None = None
    levels: list[str]
    marker: int = Field(ge=1)  # 1-based index into levels
    marker_label: str | None = None
    caption: Line | None = None


class Axis(Strict):
    min: float
    max: float
    step: float
    unit: str = ""
    label: str | None = None


class RangeRow(Strict):
    label: str
    claim: ClaimId | None = None
    lo: float | None = None
    hi: float | None = None
    no_data: ClaimId | None = None  # an N claim; renders a NO DATA row, never a bar

    @model_validator(mode="after")
    def _shape(self) -> "RangeRow":
        if self.no_data:
            if self.claim or self.lo is not None or self.hi is not None:
                raise ValueError("a no_data row cannot carry a claim or lo/hi values")
        elif not (self.claim and self.lo is not None and self.hi is not None):
            raise ValueError("a range row needs claim, lo and hi (or no_data)")
        elif self.lo > self.hi:
            raise ValueError("lo must be <= hi")
        return self


class RangeReference(Strict):
    value: float
    label: str
    claim: ClaimId  # the claim being tested by the dashed line


class RangeChart(Component):
    title: str | None = None
    axis: Axis
    rows: list[RangeRow]
    reference: RangeReference | None = None
    caption: Line | None = None


class Numeral(Strict):
    value: str
    label: Line


class DarkBox(Component):
    title: str | None = None
    numerals: list[Numeral]
    footnote: Line | None = None


class StatRow(Component):
    stats: list[Numeral]


class Opener(Component):
    n: str
    title: str
    lines: list[Line] = Field(default_factory=list)


class TimelineStep(Component):
    n: int | str
    title: str
    image: SlotId | None = None
    builds: Line
    start: Line
    move_on_when: Line
    labels: dict[str, str] = Field(default_factory=dict)  # override "Builds"/"Start"/"Move on when"


class ReadyChecklist(Component):
    title: str
    items: list[Line]


class H2HRow(Strict):
    label: str
    cells: list[Line]


class H2HTable(Component):
    columns: list[str]  # first entry labels the row-header column
    rows: list[H2HRow]
    highlight: int | None = None  # 1-based data column to accent


class Calendar(Component):
    title: str | None = None
    days: list[str]
    rows: list[str]  # row labels
    cells: list[str]  # one string per row, one char per day; "." = rest
    legend: dict[str, str]  # char → label

    @model_validator(mode="after")
    def _grid(self) -> "Calendar":
        if len(self.cells) != len(self.rows):
            raise ValueError(f"calendar has {len(self.rows)} rows but {len(self.cells)} cell strings")
        for i, row in enumerate(self.cells):
            if len(row) != len(self.days):
                raise ValueError(f"calendar row {i + 1} has {len(row)} cells, expected {len(self.days)}")
            for ch in row:
                if ch != "." and ch not in self.legend:
                    raise ValueError(f"calendar cell {ch!r} missing from legend")
        return self


class SessionTable(Component):
    title: str | None = None
    columns: list[str]
    rows: list[list[Line]]


class Rules(Component):
    title: str | None = None
    items: list[Line]


class Checklist(Component):
    title: str | None = None
    items: list[Line]


class Tracker(Component):
    title: str | None = None
    columns: list[str]
    rows: int = Field(default=6, ge=1, le=30)
    row_labels: list[str] = Field(default_factory=list)


class Image(Component):
    slot: SlotId
    height: int = Field(default=720, ge=120, le=1700)
    caption: Line | None = None


class PhotoFrame(Component):
    line: PlaceholderLine
    height: int = Field(default=560, ge=120, le=1700)


class Placeholder(Component):
    line: PlaceholderLine


class CtaBox(Component):
    title: str
    line: Line


class Safety(Component):
    title: str = "Safety first"
    items: list[Line]


class TagLegend(Component):
    tags: list[TagCode]
    title: str | None = None


BLOCK_TYPES: dict[str, type[Component]] = {
    "card": Card,
    "facts": Facts,
    "p": Para,
    "verdict": Verdict,
    "myth": Myth,
    "level_scale": LevelScale,
    "range_chart": RangeChart,
    "dark_box": DarkBox,
    "stat_row": StatRow,
    "opener": Opener,
    "timeline_step": TimelineStep,
    "ready_checklist": ReadyChecklist,
    "h2h_table": H2HTable,
    "calendar": Calendar,
    "session_table": SessionTable,
    "rules": Rules,
    "checklist": Checklist,
    "tracker": Tracker,
    "image": Image,
    "photo_frame": PhotoFrame,
    "placeholder": Placeholder,
    "cta_box": CtaBox,
    "safety": Safety,
    "tag_legend": TagLegend,
}


class BlockBase(Strict):
    kind: ClassVar[str]

    @property
    def body(self) -> Component:
        return getattr(self, self.kind)


def _make_block(kind: str, comp: type[Component]) -> type[BlockBase]:
    cls = create_model(f"{comp.__name__}Block", __base__=BlockBase, **{kind: (comp, ...)})
    cls.kind = kind
    return cls


_BLOCK_MODELS = {k: _make_block(k, v) for k, v in BLOCK_TYPES.items()}


def _block_kind(v: Any) -> str | None:
    if isinstance(v, BlockBase):
        return v.kind
    if isinstance(v, dict) and len(v) == 1:
        key = next(iter(v))
        return key if key in _BLOCK_MODELS else None
    return None


Block = Annotated[
    Union[tuple(Annotated[m, Tag(k)] for k, m in _BLOCK_MODELS.items())],  # type: ignore[misc]
    Discriminator(_block_kind),
]


# --------------------------------------------------------------------------- pages

PageType = Literal[
    "cover", "short_version", "at_a_glance", "tags_safety", "section_opener", "ladder",
    "head_to_head", "plan", "myths", "story", "checklist", "next_step", "sources",
]
PAGE_TYPES: tuple[str, ...] = PageType.__args__  # type: ignore[attr-defined]


class Page(Strict):
    type: PageType
    kicker: str | None = None
    title: str | None = None
    lede: Line | None = None
    section_number: str | None = None  # section_opener
    image: SlotId | None = None  # cover hero
    badge: str | None = None  # cover
    footer_note: str | None = None
    blocks: list[Block] = Field(default_factory=list)

    # filled by the loader, not from YAML
    id: str = Field(default="", exclude=True)
    file: str = Field(default="", exclude=True)

    @model_validator(mode="after")
    def _required(self) -> "Page":
        if self.type not in ("cover", "sources") and not self.title:
            raise ValueError(f"page type {self.type!r} needs a title")
        if self.type == "section_opener" and not self.section_number:
            raise ValueError("section_opener pages need section_number")
        return self
